# Header
menu:
  Home: /
  Archives: /archives
  Money: /tags/Money/
  Issues: /tags/Issues
  Lifestyle: /tags/Lifestyle
  Politics: /tags/Politics
  Pulse: /tags/Pulse
  Editorials: /tags/Editorials
  News: /tags/News
  Rss:
    url: atom.xml
    icon: rss

# Title on top left of menu. Leave empty to use main blog title
menu_title: Liberal America

# URL of the Home page image
index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
linkedin_url:
mailto:
