language: node_js
node_js:
- '6.1'
branches:
  only:
    - master
before_install:
- git submodule update --init --recursive
- openssl aes-256-cbc -K $encrypted_f9a584f50a17_key -iv $encrypted_f9a584f50a17_iv
  -in deploy_key.enc -out deploy_key -d
script:
- bash ./deploy.sh
